import type { Food } from './db';

export const sampleIndianFoods: Food[] = [
  {
    id: 1,
    name: 'Roti',
    brand: 'Homemade',
    category: 'Bread',
    per100g: { kcal: 264, protein: 8.5, carbs: 49.8, fat: 2.7 },
    tags: ['bread', 'whole wheat', 'traditional'],
    source: 'user',
    verified: true,
    lastUpdated: new Date().toISOString(),
    searchCount: 0,
    servings: [
      { label: '1 piece', grams: 30 },
      { label: '2 pieces', grams: 60 },
    ],
  },
  {
    id: 2,
    name: 'Dal Makhani',
    brand: 'Restaurant',
    category: 'Legumes',
    per100g: { kcal: 120, protein: 7.2, carbs: 18.5, fat: 3.1 },
    tags: ['lentils', 'curry', 'protein'],
    source: 'user',
    verified: true,
    lastUpdated: new Date().toISOString(),
    searchCount: 0,
    servings: [
      { label: '1 cup', grams: 200 },
      { label: '1/2 cup', grams: 100 },
    ],
  },
  {
    id: 3,
    name: 'Basmati Rice',
    brand: 'Premium',
    category: 'Grains',
    per100g: { kcal: 130, protein: 2.7, carbs: 28.2, fat: 0.3 },
    tags: ['rice', 'long grain', 'aromatic'],
    source: 'user',
    verified: true,
    lastUpdated: new Date().toISOString(),
    searchCount: 0,
    servings: [
      { label: '1 cup cooked', grams: 150 },
      { label: '1/2 cup cooked', grams: 75 },
    ],
  },
  {
    id: 4,
    name: 'Chicken Curry',
    brand: 'Homemade',
    category: 'Meat',
    per100g: { kcal: 180, protein: 22.5, carbs: 8.2, fat: 7.8 },
    tags: ['chicken', 'curry', 'spicy', 'protein'],
    source: 'user',
    verified: true,
    lastUpdated: new Date().toISOString(),
    searchCount: 0,
    servings: [
      { label: '1 serving', grams: 250 },
      { label: '1/2 serving', grams: 125 },
    ],
  },
  {
    id: 5,
    name: 'Paneer Tikka',
    brand: 'Restaurant',
    category: 'Dairy',
    per100g: { kcal: 265, protein: 18.2, carbs: 4.8, fat: 19.5 },
    tags: ['paneer', 'grilled', 'vegetarian', 'protein'],
    source: 'user',
    verified: true,
    lastUpdated: new Date().toISOString(),
    searchCount: 0,
    servings: [
      { label: '1 piece', grams: 50 },
      { label: '2 pieces', grams: 100 },
    ],
  },
  {
    id: 6,
    name: 'Aloo Gobi',
    brand: 'Homemade',
    category: 'Vegetables',
    per100g: { kcal: 95, protein: 3.2, carbs: 15.8, fat: 2.1 },
    tags: ['potato', 'cauliflower', 'vegetarian', 'curry'],
    source: 'user',
    verified: true,
    lastUpdated: new Date().toISOString(),
    searchCount: 0,
    servings: [
      { label: '1 cup', grams: 150 },
      { label: '1/2 cup', grams: 75 },
    ],
  },
  {
    id: 7,
    name: 'Naan Bread',
    brand: 'Tandoor',
    category: 'Bread',
    per100g: { kcal: 310, protein: 8.2, carbs: 58.5, fat: 4.8 },
    tags: ['bread', 'leavened', 'tandoor'],
    source: 'user',
    verified: true,
    lastUpdated: new Date().toISOString(),
    searchCount: 0,
    servings: [
      { label: '1 piece', grams: 80 },
      { label: '1/2 piece', grams: 40 },
    ],
  },
  {
    id: 8,
    name: 'Mango Lassi',
    brand: 'Fresh',
    category: 'Beverages',
    per100g: { kcal: 85, protein: 2.1, carbs: 16.8, fat: 1.2 },
    tags: ['yogurt', 'mango', 'drink', 'refreshing'],
    source: 'user',
    verified: true,
    lastUpdated: new Date().toISOString(),
    searchCount: 0,
    servings: [
      { label: '1 glass', grams: 250 },
      { label: '1/2 glass', grams: 125 },
    ],
  },
  {
    id: 9,
    name: 'Samosa',
    brand: 'Street Food',
    category: 'Snacks',
    per100g: { kcal: 320, protein: 6.8, carbs: 42.5, fat: 14.2 },
    tags: ['snack', 'fried', 'pastry', 'potato'],
    source: 'user',
    verified: true,
    lastUpdated: new Date().toISOString(),
    searchCount: 0,
    servings: [
      { label: '1 piece', grams: 60 },
      { label: '2 pieces', grams: 120 },
    ],
  },
  {
    id: 10,
    name: 'Gulab Jamun',
    brand: 'Sweet Shop',
    category: 'Desserts',
    per100g: { kcal: 380, protein: 4.2, carbs: 68.5, fat: 12.8 },
    tags: ['dessert', 'sweet', 'milk solids', 'syrup'],
    source: 'user',
    verified: true,
    lastUpdated: new Date().toISOString(),
    searchCount: 0,
    servings: [
      { label: '1 piece', grams: 25 },
      { label: '2 pieces', grams: 50 },
    ],
  },
  {
    id: 11,
    name: 'Masala Chai',
    brand: 'Homemade',
    category: 'Beverages',
    per100g: { kcal: 45, protein: 1.8, carbs: 8.2, fat: 1.5 },
    tags: ['tea', 'spiced', 'milk', 'traditional'],
    source: 'user',
    verified: true,
    lastUpdated: new Date().toISOString(),
    searchCount: 0,
    servings: [
      { label: '1 cup', grams: 200 },
      { label: '1/2 cup', grams: 100 },
    ],
  },
  {
    id: 12,
    name: 'Biryani Rice',
    brand: 'Restaurant',
    category: 'Grains',
    per100g: { kcal: 145, protein: 3.1, carbs: 31.5, fat: 1.2 },
    tags: ['rice', 'biryani', 'spiced', 'aromatic'],
    source: 'user',
    verified: true,
    lastUpdated: new Date().toISOString(),
    searchCount: 0,
    servings: [
      { label: '1 cup', grams: 180 },
      { label: '1/2 cup', grams: 90 },
    ],
  },
  {
    id: 13,
    name: 'Tandoori Chicken',
    brand: 'Tandoor',
    category: 'Meat',
    per100g: { kcal: 165, protein: 25.8, carbs: 2.1, fat: 6.2 },
    tags: ['chicken', 'tandoori', 'grilled', 'spicy'],
    source: 'user',
    verified: true,
    lastUpdated: new Date().toISOString(),
    searchCount: 0,
    servings: [
      { label: '1 piece', grams: 120 },
      { label: '1/2 piece', grams: 60 },
    ],
  },
  {
    id: 14,
    name: 'Raita',
    brand: 'Homemade',
    category: 'Dairy',
    per100g: { kcal: 75, protein: 3.8, carbs: 6.2, fat: 4.1 },
    tags: ['yogurt', 'side dish', 'cooling', 'vegetarian'],
    source: 'user',
    verified: true,
    lastUpdated: new Date().toISOString(),
    searchCount: 0,
    servings: [
      { label: '1 cup', grams: 150 },
      { label: '1/2 cup', grams: 75 },
    ],
  },
  {
    id: 15,
    name: 'Papadum',
    brand: 'Traditional',
    category: 'Snacks',
    per100g: { kcal: 280, protein: 8.5, carbs: 52.8, fat: 2.1 },
    tags: ['crispy', 'lentil', 'appetizer', 'thin'],
    source: 'user',
    verified: true,
    lastUpdated: new Date().toISOString(),
    searchCount: 0,
    servings: [
      { label: '1 piece', grams: 15 },
      { label: '2 pieces', grams: 30 },
    ],
  },
];

export const defaultGoals = {
  kcal: 2000,
  protein: 150,
  carbs: 200,
  fat: 67,
};
